#!/bin/bash
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblCRGKeyword > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblCRGKeyword.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblDesign > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblDesign.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblExportDef > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblExportDef.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblHealthCareCondition > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblHealthCareCondition.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblImportDef > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblImportDef.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblImportedReports > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblImportedReports.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblMethodofAllocation > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblMethodofAllocation.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblMyGroupInformation > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblMyGroupInformation.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblOptions > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblOptions.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblOutcome > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblOutcome.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblParticipant > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblParticipant.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblPublicationType > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblPublicationType.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblReportCRGKeyword > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblReportCRGKeyword.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblReportExternalID > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblReportExternalID.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblReportReviewer > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblReportReviewer.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblReview > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblReview.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblReviewer > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblReviewer.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblReviewerImport > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblReviewerImport.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblReviewerKeyword > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblReviewerKeyword.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblReviewImport > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblReviewImport.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblReviewTopic > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblReviewTopic.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblSavedSearch > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblSavedSearch.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblSearchFieldsDef > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblSearchFieldsDef.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblSearchLines > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblSearchLines.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblStudy > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblStudy.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblStudyCRGInterest > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblStudyCRGInterest.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblStudyDesign > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblStudyDesign.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblStudyHealthCareCondition > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblStudyHealthCareCondition.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblStudyIntervention > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblStudyIntervention.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblStudyMethod > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblStudyMethod.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblStudyOutcome > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblStudyOutcome.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblStudyParticipant > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblStudyParticipant.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblStudyReport > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblStudyReport.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblStudyReview > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblStudyReview.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblStudyTopic > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblStudyTopic.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblSwitchboardItems > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblSwitchboardItems.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblTempRefToRev > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblTempRefToRev.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblTempSearchLine > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblTempSearchLine.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblTopic > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblTopic.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblTopicImport > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblTopicImport.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblTypeofReport > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblTypeofReport.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblUnlinkedStudies > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblUnlinkedStudies.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblIntervention > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblIntervention.csv
mdb-export /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatBE.mdb tblReport > /home/lena/Dokumente/Master/dissertation/Data/CSZG/MeerKatCSV/tblReport.csv
